#pragma once

#include "strikeengine/ecs/Component.hpp"
#include <glm/glm.hpp>

namespace StrikeEngine {

    /**
     * @brief Holds the acceleration command generated by a guidance system.
     *
     * This component acts as a communication channel between the GuidanceSystem
     * and the ControlSystem (autopilot). The GuidanceSystem writes the desired
     * acceleration vector into this component, and the ControlSystem reads it
     * to determine how to deflect the control surfaces.
     */
    struct AutopilotCommandComponent final : public Component {
        /**
         * @brief The commanded acceleration vector in the world frame, measured in G's.
         * For example, a value of (0, 20, 0) would command a 20g pull "up".
         */
        glm::dvec3 commanded_acceleration_g{0.0};
    };

} // namespace StrikeEngine
